### ISSUE TITLE
Add integration tests for showing similar series

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#996] opened 2019-01-12 11:54 UTC
The puzzle `967-8622ce19` from #967 has to be resolved: 

https://github.com/php-coder/mystamps/blob/ff255631214be2581b2cf1533bda2e68644e5e9c/src/main/webapp/WEB-INF/views/series/info.html#L342-L342

The puzzle was created by Slava Semushin on 12-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by php-coder** [comment] 2019-01-12 11:59
Duplicate of #993

**Closed by php-coder** 2019-01-12 11:59 UTC
Labels: resolution/duplicate
