### ISSUE TITLE
/series/import/request/{id}(imageUrl): add validation for non-empty file

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1582] opened 2022-07-09 11:07 UTC
The puzzle `709-6a277942` from #709 has to be resolved: 

https://github.com/php-coder/mystamps/blob/77cf2a70ffad00eb1d7508fba56f627050f87ef3/src/main/java/ru/mystamps/web/feature/series/importing/ImportSeriesForm.java#L95-L95

The puzzle was created by Slava Semushin on 20-Jun-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by php-coder** [comment] 2022-07-09 14:21
Duplicate of #728

**Closed by php-coder** 2022-07-09 14:21 UTC
Labels: techdebt, resolution/duplicate
