### ISSUE TITLE
CategoryController: remove dependency on SeriesService by moving showInfoBySlug() method

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1053] opened 2019-06-16 15:02 UTC
The puzzle `927-dc17d3cc` from #927 has to be resolved: 

https://github.com/php-coder/mystamps/blob/6fc61a2d20b5b13f4eb9a47e5b6f45267f5b11c2/src/main/java/ru/mystamps/web/feature/category/CategoryController.java#L88-L88

The puzzle was created by Slava Semushin on 16-Jun-19.

**Comment by mukeshk** [comment] 2019-09-18 09:48
Is id duplicate of 1052?

**Comment by php-coder** [comment] 2019-09-18 10:14
> Is id duplicate of 1052?

No, they're about different classes: CategoryController vs CountryController but yes they are mostly identical.

**Closed** 2019-10-08 21:39 UTC
Labels: refactoring, techdebt
