### ISSUE TITLE
Series import: add integration test for the case when parsed value don't match database

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#747] opened 2017-12-04 23:07 UTC
The puzzle `684-b075a77e` (from #684) in [`src/main/java/ru/mystamps/web/service/SeriesImportServiceImpl.java`](https://github.com/php-coder/mystamps/blob/4ed41b45ab3bb7f8c3d45566db348af33f8552cc/src/main/java/ru/mystamps/web/service/SeriesImportServiceImpl.java#L182-L183) has to be resolved: "Series import: add integration test for the case when parsed value don't match database"

https://github.com/php-coder/mystamps/blob/4ed41b45ab3bb7f8c3d45566db348af33f8552cc/src/main/java/ru/mystamps/web/service/SeriesImportServiceImpl.java#L182-L183

The puzzle was created by Slava Semushin on 04-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by php-coder** [comment] 2017-12-06 22:04
Unfortunately, because of bug in the 0pdd it created a duplicated issue for the same puzzle.

Duplicate of #748

**Closed by php-coder** 2017-12-06 22:04 UTC
Labels: area/integration tests, techdebt
